# Database connection settings
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/hotel_repository
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver

# Spring date settings
#  mvc:
#    format:
#      date: iso

# Liquibase connection settings
  liquibase:
    default-schema: hotel_schema

# Hibernate settings
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    open-in-view: false

# Logger settings
logging:
  level:
    root: INFO
  file:
    name: hotel.log
    path: /

app:
  image:
    bucket: C:\Users\Admin\IdeaProjects\hotel-booking-manager-spring\service\images
