# Database connection settings
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/hotel_repository
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver

# Hibernate settings
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.current_session_context_class: thread

# Logger settings
logging:
  level:
    root: WARN
    com.bolun.hotel.repository.AbstractRepository: INFO
  file:
    name: hotel.log
    path: /