# Database connection settings
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/hotel_repository
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver

# Liquibase connection settings
  liquibase:
    default-schema: hotel_schema

# Hibernate settings
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    open-in-view: false

# Logger settings
logging:
  level:
    root: INFO
  file:
    name: hotel.log
    path: /