# Database connection settings
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/hotel_repository
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver

  # Liquibase connection settings
  liquibase:
    default-schema: hotel_schema

  # Hibernate settings
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
        jcache:
          provider: org.ehcache.jsr107.EhcacheCachingProvider
          config: classpath:ehcache.xml
        cache.default_cache_concurrency_strategy: READ_WRITE
    open-in-view: false

# Logger settings
logging:
  level:
    root: INFO
  file:
    name: hotel.log
    path: /

# Images base location
app:
  image:
    bucket: C:\Users\Admin\IdeaProjects\hotel-booking-manager-spring\service\images

order.adult.age: 18


